import { MatcheConstraint, NumberConstraint, OneOfConstraint, ReferenceConstraint, SimpleConstraint, TestConstraint, WhenConstraint } from "./resolvers/types";
export declare const required: (message?: string) => SimpleConstraint;
export declare const url: (message?: string) => SimpleConstraint;
export declare const email: (message?: string) => SimpleConstraint;
export declare const uuid: (message?: string) => SimpleConstraint;
export declare const matches: (regexp?: RegExp, message?: string) => MatcheConstraint;
export declare const min: (value: number, message?: string) => NumberConstraint;
export declare const max: (value: number, message?: string) => NumberConstraint;
export declare const positive: (message?: string) => SimpleConstraint;
export declare const negative: (message?: string) => SimpleConstraint;
export declare const integer: (message?: string) => SimpleConstraint;
export declare const lessThan: (ref: string | number, message?: string) => ReferenceConstraint;
export declare const moreThan: (ref: string | number, message?: string) => ReferenceConstraint;
export declare const length: (value: number, message?: string) => NumberConstraint;
export declare const test: (ref: string, message: string | undefined, test: (val: any) => boolean) => TestConstraint;
export declare const when: (ref: string, test: (val: any) => boolean, then: object, otherwise: object) => WhenConstraint;
export declare const oneOf: (arrayOfValues: any[], message: string) => OneOfConstraint;
