name: test action
on:
  workflow_dispatch:
        
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.2.0
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: '16'
    #format sources
    - name: format sources
      id: fmt
      run: |
        echo "::set-output name=DIFF::30"
    - name: Commit formatted sources
      if: steps.fmt.outputs.DIFF != '0'
      run: |
        echo "${steps.fmt.outputs.DIFF}"
        
        
