name: test action
on:
  workflow_dispatch:
        
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.2.0
    #format sources
    - name: format sources
      id: fmt
      run: echo 'format source'
    - uses: technote-space/get-diff-action@v4
      id: git-diff
      with:
        PATTERNS: +(src|__tests__)/**/*.ts
    - name: Commit formatted sources
      run: |
        echo '${{ env.GIT_DIFF }}' | jq .
        echo '${{ steps.git-diff.outputs.diff }}' | jq .
        echo '${{ steps.git-diff.outputs.count }}' | jq .
        echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"
        
        
